### PR TITLE
Support untagged unions with informal tag encoding

### PR DESCRIPTION
**Pull request by m-bock**
This PR adds two functions to the library

`toTaggedBy`
`fromTaggedBy`

They work similar to the existing functions but take an additional option that can configure how the conversion happens if the union types has some inherent tag encoding. As it's quite common in TS to have something like `{tag : "foo", value: { data ..}`

If it can be statically proven that each case follows this pattern, the case discrimination can be done based on the tag.

Benefits are:
  - No need for `HasRuntimeType` instances
  - Performance enhancement because only the tag is compared not the whole structure for each case

See tests for some concrete examples.

What do you think about it? Is this well suited in this library or should I publish it somewhere else?

### CODE REVIEW

**Comment by sigma-andex** [comment]
Will have a deeper look at it tomorrow, but at first look this is amazing!

**Comment by m-bock** [comment]
Cool, take your time!

**Comment by m-bock** [comment]
I think I changed my mind about this topic. This was mainly needed for FFI and I realized, actually we already have the "Variant" type that works like a union with tags. The only problem is just that the runtime encoding of Variant does not always match the encoding on the JS side. So I created this package: [purescript-variant-encodings](https://github.com/thought2/purescript-variant-encodings) which provides alternative Variant encoding types and conversions to and from Variant.
I think this is a much better solution, I think I would not merge this one anymore.

**Comment by sigma-andex** [comment]
Maybe that's something that could even be added to `purescript-variant` directly. Add extra methods to provide a custom `VariantRep` https://github.com/natefaubion/purescript-variant/blob/master/src/Data/Variant/Internal.purs#L44 
Waiting for the day that Purescript gets native support for polymorphic variants...

**Comment by m-bock** [comment]
yes, native variants would be a very consequent feature. I have this package [purescript-labeled-data](https://github.com/thought2/purescript-labeled-data) which can convert records and variants to and from ADTs.
On the readme I write a bit about variants as the "labeled sum type" in analogy to records as "labeled product type". There's also a syntax proposal for native variants.

I am not sure if the variant-encodings would be integrated into the variant package one day. That would mean that it would have to deal with this subtle restrictions of flat encodings: fields can only be records, the type tag must not appear as key. I think it's better to solve that separately.

Ok, I'll close this PR, I think it's not needed anymore. But it was a productive intermediate step.

**Pull request closed without merging**
